import type { Step, Trigger, WorkflowSpec } from "@cogwork/spec";

/**
 * Deterministic spec → readable TypeScript (COGWORK_CONTEXT.md §9 codegen).
 * Export-only — NOT executed at runtime. Exists for portability, audit, and the
 * "own your workflow as code" story.
 */

function camel(id: string): string {
  return id.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
}

function triggerComment(t: Trigger): string {
  switch (t.type) {
    case "manual":
      return "// Trigger: manual";
    case "webhook":
      return `// Trigger: webhook POST /api/hooks/${t.path}`;
    case "schedule":
      return `// Trigger: schedule "${t.cron}" (${t.timezone})`;
  }
}

function stepMethod(step: Step): string {
  const lines: string[] = [];
  const decorators: string[] = [];
  if (step.forEach) decorators.push(`@forEach(${JSON.stringify(step.forEach)})`);
  if (step.condition) decorators.push(`@when(${JSON.stringify(step.condition)})`);
  if (step.approval) decorators.push(`@approval(${JSON.stringify(step.approval)})`);
  for (const d of decorators) lines.push(`  // ${d}`);
  lines.push(`  async ${camel(step.id)}(ctx: RunContext) {`);
  lines.push(`    return ctx.call(${JSON.stringify(step.tool)}, ${JSON.stringify(step.params, null, 2)
    .split("\n")
    .join("\n    ")});`);
  if (step.outputs?.length) {
    lines.push(`    // outputs: ${step.outputs.join(", ")}`);
  }
  lines.push(`  }`);
  return lines.join("\n");
}

function className(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9]+/g, " ").trim();
  const pascal = cleaned
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  return (pascal || "Workflow") + "Workflow";
}

export function generateCode(spec: WorkflowSpec): string {
  const header = [
    `// ${spec.name}`,
    spec.description ? `// ${spec.description}` : "",
    "//",
    "// Generated by Cogwork — export only. Cogwork runs the spec, not this code.",
    'import type { RunContext } from "@cogwork/engine";',
    "",
    triggerComment(spec.trigger),
    `export class ${className(spec.name)} {`,
  ]
    .filter(Boolean)
    .join("\n");

  const methods = spec.steps.map(stepMethod).join("\n\n");

  return `${header}\n${methods}\n}\n`;
}
